// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYK01dgFCVS0tsDcoBF0iCoZ0SuEu8Aws',
    appId: '1:570979417028:web:9d76475a72c581f77f4291',
    messagingSenderId: '570979417028',
    projectId: 'task-two-944fe',
    authDomain: 'task-two-944fe.firebaseapp.com',
    storageBucket: 'task-two-944fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO8Rv0GC2g_vrcVKLmSEncqV4V_jvnl74',
    appId: '1:570979417028:android:fba90d354a9b035d7f4291',
    messagingSenderId: '570979417028',
    projectId: 'task-two-944fe',
    storageBucket: 'task-two-944fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTXE4fsaORQ5L_gdcL7kYij_tRg56Ni3U',
    appId: '1:570979417028:ios:f1990deaa9fe74ed7f4291',
    messagingSenderId: '570979417028',
    projectId: 'task-two-944fe',
    storageBucket: 'task-two-944fe.appspot.com',
    iosClientId: '570979417028-et6jl61vj9inrt609j4f0ov6mjgf9pb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTXE4fsaORQ5L_gdcL7kYij_tRg56Ni3U',
    appId: '1:570979417028:ios:f1990deaa9fe74ed7f4291',
    messagingSenderId: '570979417028',
    projectId: 'task-two-944fe',
    storageBucket: 'task-two-944fe.appspot.com',
    iosClientId: '570979417028-et6jl61vj9inrt609j4f0ov6mjgf9pb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskTwo',
  );
}
